load('//io:rules.bzl', 'java_module')

java_module(
	name = 'common',
	exported_deps = [
		'//lib/google/common:common',
		'//lib/immutables/value:annotations',
		'//lib/javax/annotation:annotation',
	],
)

java_annotation_processor(
	name = 'immutables',
	deps = [
		':common',
		'//lib/immutables/value:value',
	],
	processor_class = 'org.immutables.processor.ProxyProcessor',
	visibility = ['PUBLIC'],
)
