java_package(
  name = 'fixture',
  deps = [
    '//src/io/immutables/lang:lang'
  ] + lib_test,
  res = glob(["*.im"]),
  processors = ['io.immutables.lang.processor.SourceRunProcessor'],
  processor_deps = [
    '//src:metainf_annotations',
    '//src/io/immutables/lang/processor:processor',
  ])
