load('//io:rules.bzl', 'java_module')

java_module(
	name = 'codec',
  deps = [
    '//io/common:common',
		'//lib/square/moshi:moshi',
		'//lib/square/okio:okio',
		'//lib/javax/annotation:annotation',
  ],
  exported_deps = [
    '//lib/immutables/data:data',
  ],
  test_deps = [
  	'//io/that:that',
  ],
  plugins = [
		'//io/common:immutables',
  ],
)
