java_package(
	name = 'fixture',
  deps = [
  	  '//src/io/immutables/collect:collect',
  	  '//src/io/immutables/lang:lang',
  	  '//old/io/immutables/lang/type22:type22',
  	  '//src/io/immutables/grammar:grammar'
  ])
