java_package(
  name = 'processor',
  srcs = glob(['*.java']),
  res = glob(['*.generator']),
  deps = [
    '//lib:immutables_trees',
    '//lib:immutables_generator',
    '//src/io/immutables/grammar:grammar',
    '//src/io/immutables/collect:collect',
  ],
  processors = [
    'org.immutables.generator.processor.Processor'
  ],
  processor_deps = [
    '//lib:immutables_generator'
  ]
)