java_package(
	name = 'typing',
  deps = [
  	  '//src/io/immutables/collect:collect',
  	  '//src/io/immutables/lang:lang',
  	  '//src/io/immutables/lang/type:type',
  	  '//src/io/immutables/grammar:grammar'
  ])
