load('//mod:rules.bzl', 'java_module')

java_module(
	name = 'log',
  deps = [
	  '//lib/immutables/value:annotations',
    '//mod/common:common',
    '//lib/postresql:postresql',
  ],
  plugins = [
    '//lib/immutables/value:processor'
  ],
  maven_coords = 'io.immutables:log:0.0.1',
)
