load('//io:rules.bzl', 'java_module')

java_module(
	name = 'net',
	exported_deps = [
		'//lib/google/common:common',
	],
	provided_deps = [
		'//lib/javax/annotation:annotation',
	],
  artifact = True,
)
