load('//lib:rules.bzl', 'java_module', 'java_test_vm_args')

java_library(
	name = 'lang',
	srcs = glob(['src/io/immutables/lang/*.java']),
	resources = glob(['src/io/immutables/lang/*.grammar']),
	deps = [
		'//lib/immutables/value:annotations',
	],
	exported_deps = [
		'//mod/common:common',
		'//mod/grammar:grammar',
		'//lib/immutables/trees:trees',
	],
	resources_root = 'src',
	extra_arguments = ['-Aresources.root={}/src'.format(package_name())],
	plugins = [
		'//mod/grammar:processor',
		'//mod/common:immutables',
	],
)

java_library(
	name = 'sourcerun_annotation',
	srcs = glob(['test/io/immutables/lang/*.java']),
	resources_root = 'test',
)

java_library(
	name = 'sourcerun_processor_generator',
	srcs = [],
	resources = glob(['test/io/immutables/lang/processor/*.generator']),
	resources_root = 'test',
)

java_library(
	name = 'sourcerun_processor_library',
	srcs = glob(['test/io/immutables/lang/processor/*.java']),
	deps = [
		':lang',
		':sourcerun_annotation',
		':sourcerun_processor_generator',
		'//lib/immutables/value:annotations',
		'//lib/immutables/generator:processor',
		'//mod/common:common',
	],
	annotation_processors = [
		'org.immutables.processor.ProxyProcessor',
		'org.immutables.generator.processor.Processor',
	],
	annotation_processor_deps = [
		'//lib/immutables/trees:trees',
		'//lib/immutables/value:value',
		'//lib/immutables/generator:processor',
	],
	resources_root = 'test',
)

java_annotation_processor(
	name = 'sourcerun_processor',
	deps = [
		':sourcerun_processor_library',
	],
	processor_class = 'io.immutables.lang.processor.SourceRunProcessor',
)

java_test(
	name = 'test',
	srcs = glob(['test/io/immutables/lang/fixture/*.java']),
	resources = glob(['test/io/immutables/lang/fixture/*.test.im']),
	deps = [
		':lang',
		':sourcerun_annotation',
		'//mod/that:that',
		'//lib/junit:junit',
	],
	extra_arguments = ['-Aresources.root={}/test'.format(package_name())],
	resources_root = 'test',
	plugins = [
		':sourcerun_processor',
		'//mod/common:immutables',
	],
	vm_args = java_test_vm_args(),
)
